"""user something

Revision ID: 29f7c704daf1
Revises: 31e5f7a7b4ec
Create Date: 2021-05-10 01:39:32.078634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f7c704daf1'
down_revision = '31e5f7a7b4ec'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
