"""adding some changes to video item db model

Revision ID: 31e5f7a7b4ec
Revises: e8d425a6f497
Create Date: 2021-05-10 00:33:53.423495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e5f7a7b4ec'
down_revision = 'e8d425a6f497'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txt', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('bob_link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_items',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=1200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['video_items.id'], name='fk_comment_item_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_comment_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_topics',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_topic_team'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['video_items.id'], name='fk_like_item'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_like_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_items',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['video_items.id'], name='fk_tag_item'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_item_tag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_items',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['video_items.id'], name='fk_item_user'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_item'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('views',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seconds_in_video', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['video_items.id'], name='fk_view_item'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_view_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_items',
    sa.Column('last_modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('topic_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['video_items.id'], name='fk_topic_item_id'),
    sa.ForeignKeyConstraint(['topic_id'], ['content_topics.id'], name='fk_content_topic_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_items')
    op.drop_table('views')
    op.drop_table('user_items')
    op.drop_table('tag_items')
    op.drop_table('likes')
    op.drop_table('content_topics')
    op.drop_table('comments')
    op.drop_table('video_items')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('tags')
    # ### end Alembic commands ###
